mqtt:
  broker: 127.0.0.1:1883
  user: root
  pass: root
  topicToSubscribe: device/attributes
  topicToPublish: device/attributes
  topicToStatus: device/status
  topicToProgress: ota/device/progress
  topicToInfrom: ota/device/infrom
  gateway_topic: gateway/attributes
  #消息服务质量 0：消息最多传递一次，如果当时客户端不可用，则会丢失该消息。1：消息传递至少 1 次。2：消息仅传送一次。
  qos: 0

api:
  http_host: 127.0.0.1:8083
