switch:
  type: 'app'
  name: '开关控制器'
  device: '开关控制器v1.0'
  description: ''
  version: '1.0.0'
  author: '字段【开关状态（0关闭，1打开）】'
  email: ''
  widgets:
    switch_btn:
      name: '开关'
      description: '开关'
      receiver: ''
      thumbnail: '/switch.png'
      template: 'switch-btn'
      fields:
        status:
          name: '开关状态'
          type: 2
          symbol: ''