name: copyImageToJiHu

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Jihulab Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.jihulab.com
        username: ${{ secrets.JH_USER }}
        password: ${{ secrets.JH_PASS }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Jihulab Docker Hub2
      run: |
         skopeo copy docker://ghcr.io/thingspanel/thingspanel-go:v1.1.3 docker://registry.jihulab.com/thingspanel/docker-images/thingspanel-go:v1.1.3
    #- name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub
     # run: |
     #    skopeo copy docker://docker.io/timescale/timescaledb:latest-pg14 docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/timescaledb:latest-pg14
#
    #- name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub1
   #   run: |
     #    skopeo copy docker://docker.io/redis:latest docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/redis:latest
#
